// Work around older JS's w/out freeze()
if(Object.freeze === undefined) { Object.freeze = function(x) { return x; } }

// Attempt to lookup a value in the specified table. If the optional
// throwIfNotFound is truthy throw an error if no match is found otherwise
// return the original value. FIXME: This is needlessly slow!
exports.lookup = function(table, value, throwIfNotFound) {
  for(var k in table) {
    if(table[k].value === value) { return table[k]; }
  }
  return value;
}

exports.tables = {
  // Code Table 0.0
  Discipline: Object.freeze({
    METEOROLOGICAL:     { name: 'Meteorological Products', value: 0 },
    HYDROLOGICAL:       { name: 'Hydrological Products', value: 1 },
    LAND_SURFACE:       { name: 'Land Surface Products', value: 2 },
    SATELLITE_REMOTE:   { name: 'Satellite Remote Sensing Products', value: 3 },
    SPACE:              { name: 'Space Weather Products', value: 4 },
    OCEANOGRAPHIC:      { name: 'Oceanographic Products ', value: 10 },
    MISSING:            { name: 'Missing', value: 255 },
  }),

  // Code Table 1.0
  Center: Object.freeze({
    MELBOURNE_1: { name: 'Melbourne (WMC)', value: 1 },
    MELBOURNE_2: { name: 'Melbourne (WMC)', value: 2 },
    MELBOURNE_3: { name: 'Melbourne (WMC)', value: 3 },
    MELBOURNE_4: { name: 'Melbourne (RSMC)', value: 67 },
    MOSCOW_1: { name: 'Moscow (WMC)', value: 4 },
    MOSCOW_2: { name: 'Moscow (WMC)', value: 5 },
    MOSCOW_3: { name: 'Moscow (WMC)', value: 6 },
    MOSCOW_4: { name: 'Moscow (RSMC/RAFC)', value: 76 },
    US_NCEP: { name: 'US National Weather Service - NCEP (WMC)', value: 7 },
    US_NWSTG: { name: 'US National Weather Service - NWSTG (WMC)', value: 8 },
    US_OTHER: { name: 'US National Weather Service - Other (WMC)', value: 9 },
    CAIRO_1: { name: 'Cairo (RSMC/RAFC)', value: 10 },
    CAIRO_2: { name: 'Cairo (RSMC/RAFC)', value: 11 },
    DAKAR_1: { name: 'Dakar (RSMC/RAFC)', value: 12 },
    DAKAR_2: { name: 'Dakar (RSMC/RAFC)', value: 13 },
    NAIROBI_1: { name: 'Nairobi (RSMC/RAFC)', value: 14 },
    NAIROBI_2: { name: 'Nairobi (RSMC/RAFC)', value: 15 },
    CASABLANCA: { name: 'Casablanca (RSMC)', value: 16 },
    TUNIS: { name: 'Tunis (RSMC)', value: 17 },
    TUNIS_CASABLANCA_1: { name: 'Tunis-Casablanca (RSMC)', value: 18 },
    TUNIS_CASABLANCA_2: { name: 'Tunis-Casablanca (RSMC)', value: 19 },
    LAS_PALMAS: { name: 'Las Palmas (RAFC)', value: 20 },
    ALGIERS: { name: 'Algiers (RSMC)', value: 21 },
    ACMAD: { name: 'ACMAD', value: 22 },
    MOZAMBIQUE: { name: 'Mozambique (NMC)', value: 23 },
    PRETORIA: { name: 'Pretoria (RSMC)', value: 24 },
    LA_REUNION: { name: 'La Reunion (RSMC)', value: 25 },
    KHABAROVSK_1: { name: 'Khabarovsk (RSMC)', value: 26 },
    KHABAROVSK_2: { name: 'Khabarovsk (RSMC)', value: 27 },
    NEW_DELHI_1: { name: 'New Delhi (RSMC/RAFC)', value: 28 },
    NEW_DELHI_2: { name: 'New Delhi (RSMC/RAFC)', value: 29 },
    NOVOSIBIRSK_1: { name: 'Novosibirsk (RSMC)', value: 30 },
    NOVOSIBIRSK_2: { name: 'Novosibirsk (RSMC)', value: 31 },
    TASHKENT: { name: 'Tashkent (RSMC)', value: 32 },
    JEDDAH: { name: 'Jeddah (RSMC)', value: 33 },
    TOKYO_1: { name: 'Tokyo (RSMC), Japanese Meteorological Agency', value: 34 },
    TOKYO_2: { name: 'Tokyo (RSMC), Japanese Meteorological Agency', value: 35 },
    BANKOK: { name: 'Bankok', value: 36 },
    ULAN_BATOR: { name: 'Ulan Bator', value: 37 },
    BEIJING_1: { name: 'Beijing (RSMC)', value: 38 },
    BEIJING_2: { name: 'Beijing (RSMC)', value: 39 },
    SEOUL: { name: 'Seoul', value: 40 },
    BUENOS_AIRES_1: { name: 'Buenos Aires (RSMC/RAFC)', value: 41 },
    BUENOS_AIRES_2: { name: 'Buenos Aires (RSMC/RAFC)', value: 42 },
    BRASILIA_1: { name: 'Brasilia (RSMC/RAFC)', value: 43 },
    BRASILIA_2: { name: 'Brasilia (RSMC/RAFC)', value: 44 },
    SANTIAGO: { name: 'Santiago', value: 45 },
    BRAZILIAN_SPACE_AGENCY: { name: 'Brazilian Space Agency - INPE', value: 46 },
    COLUMBIA: { name: 'Columbia (NMC)', value: 47 },
    ECUADOR: { name: 'Ecuador (NMC)', value: 48 },
    PERU: { name: 'Peru (NMC)', value: 49 },
    VENEZUELA: { name: 'Venezuela (NMC)', value: 50 },
    MIAMI: { name: 'Miami (RSMC/RAFC)', value: 51 },
    MIAMI_NATIONAL_HURRICANE_CENTER: { name: 'Miami (RSMC), National Hurricane Center', value: 52 },
    MONTREAL_1: { name: 'Canadian Meteorological Service - Montreal (RSMC)', value: 53 },
    MONTREAL_2: { name: 'Canadian Meteorological Service - Montreal (RSMC)', value: 54 },
    SAN_FRANCISCO: { name: 'San Francisco', value: 55 },
    ARINC_CENTER: { name: 'ARINC Center', value: 56 },
    US_AIR_FORCE: { name: 'US Air Force - Air Force Global Weather Center', value: 57 },
    MONTEREY: { name: 'Fleet Numerical Meteorology and Oceanography Center,Monterey,CA,USA', value: 58 },
    NOAA: { name: 'The NOAA Forecast Systems Lab, Boulder, CO, USA', value: 59 },
    NCAR: { name: 'National Center for Atmospheric Research (NCAR), Boulder, CO', value: 60 },
    ARGOS: { name: 'Service ARGOS - Landover, MD, USA', value: 61 },
    US_NAVAL_OCEANOGRAPHIC_OFFICE: { name: 'US Naval Oceanographic Office', value: 62 },
    INTERNATIONAL_RESEARCH_INSTITUDE_FOR_CLIMATE_AND_SOCIETY: { name: 'International Research Institude for Climate and Society', value: 63 },
    HONOLULU: { name: 'Honolulu', value: 64 },
    DARWIN_1: { name: 'Darwin (RSMC)', value: 65 },
    DARWIN_2: { name: 'Darwin (RSMC)', value: 66 },
    WELLINGTON_1: { name: 'Wellington (RSMC/RAFC)', value: 69 },
    WELLINGTON_2: { name: 'Wellington (RSMC/RAFC)', value: 70 },
    NADI: { name: 'Nadi (RSMC)', value: 71 },
    SINGAPORE: { name: 'Singapore', value: 72 },
    MALAYSIA: { name: 'Malaysia (NMC)', value: 73 },
    UK_MET_OFFICE_EXETER_1: { name: 'U.K. Met Office - Exeter (RSMC)', value: 74 },
    UK_MET_OFFICE_EXETER_2: { name: 'U.K. Met Office - Exeter (RSMC)', value: 75 },
    OFFENBACH_1: { name: 'Offenbach (RSMC)', value: 78 },
    OFFENBACH_2: { name: 'Offenbach (RSMC)', value: 79 },
    ROME_1: { name: 'Rome (RSMC)', value: 80 },
    ROME_2: { name: 'Rome (RSMC)', value: 81 },
    NORRKOPING_1: { name: 'Norrkoping', value: 82 },
    NORRKOPING_2: { name: 'Norrkoping', value: 83 },
    FRENCH_WEATHER_SERVICE_TOULOUSE_1: { name: 'French Weather Service - Toulouse', value: 84 },
    FRENCH_WEATHER_SERVICE_TOULOUSE_2: { name: 'French Weather Service - Toulouse', value: 85 },
    HELSINKI: { name: 'Helsinki', value: 86 },
    BELGRADE: { name: 'Belgrade', value: 87 },
    OSLO: { name: 'Oslo', value: 88 },
    PRAGUE: { name: 'Prague', value: 89 },
    EPISKOPI: { name: 'Episkopi', value: 90 },
    ANKARA: { name: 'Ankara', value: 91 },
    FRANKFURT: { name: 'Frankfurt/Main (RAFC)', value: 92 },
    LONDON: { name: 'London (WAFC)', value: 93 },
    COPENHAGEN: { name: 'Copenhagen', value: 94 },
    ROTA: { name: 'Rota', value: 95 },
    ATHENS: { name: 'Athens', value: 96 },
    EUROPEAN_SPACE_AGENCY: { name: 'European Space Agency (ESA)', value: 97 },
    EUROPEAN_CENTER_FOR_Medium_RANGE_WEATHER_FORECASTS: { name: 'European Center for Medium-Range Weather Forecasts (RSMC)', value: 98 },
    DE_BILT: { name: 'De Bilt, Netherlands', value: 99 },
    BRAZZAVILLE: { name: 'Brazzaville', value: 100 },
    ABIDJAN: { name: 'Abidjan', value: 101 },
    LIBYAN_ARAB_JAMAHIRIYA: { name: 'Libyan Arab Jamahiriya (NMC)', value: 102 },
    MADAGASCAR: { name: 'Madagascar (NMC)', value: 103 },
    MAURITIUS: { name: 'Mauritius (NMC)', value: 104 },
    NIGER: { name: 'Niger (NMC)', value: 105 },
    SEYCHELLES: { name: 'Seychelles (NMC)', value: 106 },
    UGANDA: { name: 'Uganda (NMC)', value: 107 },
    TANZANIA: { name: 'United Republic of Tanzania (NMC)', value: 108 },
    ZIMBABWE: { name: 'Zimbabwe (NMC)', value: 109 },
    HONG_KONG: { name: 'Hong-Kong', value: 110 },
    AFGHANISTAN: { name: 'Afghanistan (NMC)', value: 111 },
    BAHRAIN: { name: 'Bahrain (NMC)', value: 112 },
    BANGLADESH: { name: 'Bangladesh (NMC)', value: 113 },
    BHUTAN: { name: 'Bhutan (NMC)', value: 114 },
    CAMBODIA: { name: 'Cambodia (NMC)', value: 115 },
    KOREA: { name: '	Democratic People\'s Republic of Korea (NMC)', value: 116 },
    IRAN: { name: 'Islamic Republic of Iran (NMC)', value: 117 },
    IRAQ: { name: 'Iraq (NMC)', value: 118 },
    KAZAKHSTAN: { name: 'Kazakhstan (NMC)', value: 119 },
    KUWAIT: { name: 'Kuwait (NMC)', value: 120 },
    KYRGYZ_REPUBLIC: { name: 'Kyrgyz Republic (NMC)', value: 121 },
    LAO: { name: 'Lao People\'s Democratic Republic (NMC)', value: 122 },
    MACAO: { name: 'Macao, China', value: 123 },
    MALDIVES: { name: 'Maldives (NMC)', value: 124 },
    MYANMAR: { name: 'Myanmar (NMC)', value: 125 },
    NEPAL: { name: 'Nepal (NMC)', value: 126 },
    OMAN: { name: 'Oman (NMC)', value: 127 },
    PAKISTAN: { name: 'Pakistan (NMC)', value: 128 },
    QATAR: { name: 'Qatar (NMC)', value: 129 },
    YEMEN: { name: 'Yemen (NMC)', value: 130 },
    SRI_LANKA: { name: 'Sri Lanka (NMC)', value: 131 },
    TAJIKISTAN: { name: 'Tajikistan (NMC)', value: 132 },
    TURKMENISTAN: { name: 'Turkmenistan (NMC)', value: 133 },
    UNITED_ARAB_EMIRATES: { name: 'United Arab Emirates (NMC)', value: 134 },
    UZBEKISTAN: { name: 'Uzbekistan (NMC)', value: 135 },
    VIET_NAM: { name: 'Viet Nam (NMC)', value: 136 },
    BOLIVIA: { name: 'Bolivia (NMC)', value: 140 },
    GUYANA: { name: 'Guyana (NMC)', value: 141 },
    PARAGUAY: { name: 'Paraguay (NMC)', value: 142 },
    SURINAME: { name: 'Suriname (NMC)', value: 143 },
    URUGUAY: { name: 'Uruguay (NMC)', value: 144 },
    FRENCH_GUYANA: { name: 'French Guyana', value: 145 },
    BRAZILIAN_NAVY_HYDROGRAPHIC_CENTER: { name: 'Brazilian Navy Hydrographic Center', value: 146 },
    NATIONAL_COMMISSION_ON_SPACE_ACTIVITIES_ARGENTINA: { name: 'National Commission on Space Activities - Argentina', value: 147 },
    BRAZILIAN_DEPARTMENT_OF_AIRSPACE_CONTROL_DECEA: { name: 'Brazilian Department of Airspace Control - DECEA', value: 148 },
    ANTIGUA_AND_BARBUDA: { name: 'Antigua and Barbuda (NMC)', value: 150 },
    BAHAMAS: { name: 'Bahamas (NMC)', value: 151 },
    BARBADOS: { name: 'Barbados (NMC)', value: 152 },
    BELIZE: { name: 'Belize (NMC)', value: 153 },
    BRITISH_CARIBBEAN_TERRITORIES_CENTER: { name: 'British Caribbean Territories Center', value: 154 },
    SAN_JOSE: { name: 'San Jose', value: 155 },
    CUBA: { name: 'Cuba (NMC)', value: 156 },
    DOMINICA: { name: 'Dominica (NMC)', value: 157 },
    DOMINICAN_REPUBLIC: { name: 'Dominican Republic (NMC)', value: 158 },
    EL_SALVADOR: { name: 'El Salvador (NMC)', value: 159 },
    US_NOAA_NESDIS: { name: 'US NOAA/NESDIS', value: 160 },
    US_NOAA_OFFICE_OF_OCEANIC_AND_ATMOSPHERIC_RESEARCH: { name: 'US NOAA Office of Oceanic and Atmospheric Research', value: 161 },
    GUATEMALA: { name: 'Guatemala (NMC)', value: 162 },
    HAITI: { name: 'Haiti (NMC)', value: 163 },
    HONDURAS: { name: 'Honduras (NMC)', value: 164 },
    JAMAICA: { name: 'Jamaica (NMC)', value: 165 },
    MEXICO_CITY: { name: 'Mexico City', value: 166 },
    NETHERLANDS_ANTILLES_AND_ARUBA: { name: 'Netherlands Antilles and Aruba (NMC)', value: 167 },
    NICARAGUA: { name: 'Nicaragua (NMC)', value: 168 },
    PANAMA: { name: 'Panama (NMC)', value: 169 },
    SAINT_LUCIA: { name: 'Saint Lucia (NMC)', value: 170 },
    TRINIDAD_AND_TOBAGO: { name: 'Trinidad and Tobago (NMC)', value: 171 },
    FRENCH_DEPARTMENTS_IN_RA_IV: { name: 'French Departments in RA IV', value: 172 },
    US_NATIONAL_AERONAUTICS_AND_SPACE_ADMINISTRATION: { name: 'US National Aeronautics and Space Administration (NASA)', value: 173 },
    ISDM: { name: 'Integrated System Data Management/Marine Environmental Data Service (ISDM/MEDS) - Canada', value: 174 },
    US_COOPERATIVE_INSTITUDE_FOR_METEOROLOGICAL_SATELLITE_STUDIES: { name: 'US Cooperative Institude for Meteorological Satellite Studies', value: 176 },
    COOK_ISLANDS: { name: 'Cook Islands (NMC)', value: 190 },
    FRENCH_POLYNESIA: { name: 'French Polynesia (NMC)', value: 191 },
    TONGA: { name: 'Tonga (NMC)', value: 192 },
    VANUATU: { name: 'Vanuatu (NMC)', value: 193 },
    BRUNEI: { name: 'Brunei (NMC)', value: 194 },
    INDONESIA: { name: 'Indonesia (NMC)', value: 195 },
    KIRIBATI: { name: 'Kiribati (NMC)', value: 196 },
    MICRONESIA: { name: 'Federated States of Micronesia (NMC)', value: 197 },
    NEW_CALEDONIA: { name: 'New Caledonia (NMC)', value: 198 },
    NIUE: { name: 'Niue', value: 199 },
    PAPUA_NEW_GUINEA: { name: 'Papua New Guinea (NMC)', value: 200 },
    PHILIPPINES: { name: 'Philippines (NMC)', value: 201 },
    SAMOA: { name: 'Samoa (NMC)', value: 202 },
    SOLOMON_ISLANDS: { name: 'Solomon Islands (NMC)', value: 203 },
    NEW_ZEALAND: { name: 'Narional Institude of Water and Atmospheric Research - New Zealand', value: 204 },
    FRASCATI: { name: 'Frascati (ESA/ESRIN)', value: 210 },
    LANION: { name: 'Lanion', value: 211 },
    LISBON: { name: 'Lisbon', value: 212 },
    REYKJAVIK: { name: 'Reykjavik', value: 213 },
    MADRID: { name: 'Madrid', value: 214 },
    ZURICH: { name: 'Zurich', value: 215 },
    ARGOS_TOULOUSE: { name: 'Service ARGOS - Toulouse', value: 216 },
    BRATISLAVA: { name: 'Bratislava', value: 217 },
    BUDAPEST: { name: 'Budapest', value: 218 },
    LJUBLJANA: { name: 'Ljubljana', value: 219 },
    WARSAW: { name: 'Warsaw', value: 220 },
    ZAGREB: { name: 'Zagreb', value: 221 },
    ALBANIA: { name: 'Albania (NMC)', value: 222 },
    ARMENIA: { name: 'Armenia (NMC)', value: 223 },
    AUSTRIA: { name: 'Austria (NMC)', value: 224 },
    AZERBAIJAN: { name: 'Azerbaijan (NMC)', value: 225 },
    BELARUS: { name: 'Belarus (NMC)', value: 226 },
    BELGIUM: { name: 'Belgium (NMC)', value: 227 },
    BOSNIA_HERZEGOVINA: { name: 'Bosnia and Herzegovina (NMC)', value: 228 },
    BULGARIA: { name: 'Bulgaria (NMC)', value: 229 },
    CYPRUS: { name: 'Cyprus (NMC)', value: 230 },
    ESTONIA: { name: 'Estonia (NMC)', value: 231 },
    GEORGIA: { name: 'Georgia (NMC)', value: 232 },
    DUBLIN: { name: 'Dublin', value: 233 },
    ISRAEL: { name: 'Israel (NMC)', value: 234 },
    JORDAN: { name: 'Jordan (NMC)', value: 235 },
    LATVIA: { name: 'Latvia (NMC)', value: 236 },
    LEBANON: { name: 'Lebanon (NMC)', value: 237 },
    LITHUANIA: { name: 'Lithuania (NMC)', value: 238 },
    LUXEMBOURG: { name: 'Luxembourg', value: 239 },
    MALTA: { name: 'Malta (NMC)', value: 240 },
    MONACO: { name: 'Monaco', value: 241 },
    ROMANIA: { name: 'Romania (NMC)', value: 242 },
    SYRIAN: { name: 'Syrian Arab Republic (NMC)', value: 243 },
    MACEDONIA: { name: 'The former Yugoslav Republic of Macedonia (NMC)', value: 244 },
    UKRAINE: { name: 'Ukraine (NMC)', value: 245 },
    MOLDOVA: { name: 'Republic of Moldova (NMC)', value: 246 },
    OPERA: { name: 'Operational Programme for the Exchange of Weather RAdar Information (OPERA) - EUMETNET', value: 247 },
    CONSORTIUM_FOR_SMALL_SCALE_MODELLING: { name: 'COnsortium for Small scale MOdelling (COSMO)', value: 250 },
    EUMETSAT_OPERATIONS_CENTER: { name: 'EUMETSAT Operations Center', value: 254 },
    MISSING: { name: 'Missing Value', value: 255 },
  }),

  // Code Table 1.2
  ReferenceTimeSignificance: Object.freeze({
    ANALYSIS:           { name: 'Analysis', value: 0 },
    START_OF_FORECAST:  { name: 'Start of Forecast', value: 1 },
    VERIFICATION:       { name: 'Verification time of forecast', value: 2 },
    OBSERVATION:        { name: 'Observations time', value: 3 },
    MISSING:            { name: 'Missing', value: 255 },
  }),

  // Code Table 1.3
  ProductionStatus: Object.freeze({
    OPERATIONAL:        { name: 'Operational products', value: 0 },
    OPERATIONAL_TEST:   { name: 'Operational test products', value: 1 },
    RESEARCH:           { name: 'Research products', value: 2 },
    REANALYSIS:         { name: 'Re-analysis', value: 3 },
    MISSING:            { name: 'Missing', value: 255 },
  }),

  // Code Table 1.4
  Type: Object.freeze({
    ANALYSIS:           { name: 'Analysis products', value: 0 },
    FORECAST:           { name: 'Forecast products', value: 1 },
    ANALYSIS_AND_FORECAST:  { name: 'Analysis and forecast products', value: 2 },
    CONTROL:            { name: 'Control forecast products', value: 3 },
    PERTURBED:          { name: 'Perturbed forecast products', value: 4 },
    CONTROL_AND_PERTURBED:  { name: 'Control and perturbed forecast products', value: 5 },
    SATELLITE:          { name: 'Processed satellite observations', value: 6 },
    RADAR:              { name: 'Processed radar observations', value: 7 },
    MISSING:            { name: 'Missing', value: 255 },
  }),

  // Code Table 3.2
  EarthShape: Object.freeze({
    STD_SPHERICAL_1:    { name: 'Earth assumed spherical with radius = 6,367,470.0 m', value: 0 },
    SPHERICAL:          { name: 'Earth assumed spherical with radius specified by data producer', value: 1 },
    IAU_SPHEROID:       { name: 'Earth assumed oblate spheroid with size as determined by IAU in 1965 (major axis = 6,378,160.0 m, minor axis = 6,356,775.0 m, f = 1/297.0)', value: 2 },
    SPHEROID:           { name: 'Earth assumed oblate spheroid with major and minor axes specified by data producer', value: 3 },
    IAG_SPHEROID:       { name: 'Earth assumed oblate spheroid as defined in IAG-GRS80 model (major axis = 6,378,137.0 m, minor axis = 6,356,752.314 m, f = 1/298.257222101)', value: 4 },
    WGS84_SPHEROID:     { name: 'Earth assumed represented by WGS84 (as used by ICAO since 1998)', value: 5 },
    STD_SPHERICAL_2:    { name: 'Earth assumed spherical with radius of 6,371,229.0 m', value: 6 },
    MISSING:            { name: 'Missing', value: 255 },
  }),

  // Code Table 4.0
  ProductDefinition: Object.freeze({
    ANALYSIS_AND_FORECAST_HORIZONTAL_LEVEL_OR_LAYER: { name: 'Analysis or forecast at a horizontal level or in a horizontal layer at a point in time.', value: 0 },
  }),

  // Code Table 4.2 Meteorological products
  MeteorologicalProducts: Object.freeze({
    CATEGORY_0:   { name: 'Temperature', value: 0 },
    CATEGORY_1:   { name: 'Moisture', value: 1 },
    CATEGORY_2:   { name: 'Momentum', value: 2 },
    CATEGORY_3:   { name: 'Mass', value: 3 },
    CATEGORY_4:   { name: 'Short wave radiation', value: 4 },
    CATEGORY_5:   { name: 'Long wave radiation', value: 5 },
    CATEGORY_6:   { name: 'Cloud', value: 6 },
    CATEGORY_7:   { name: 'Thermodynamic stability indices', value: 7 },
    CATEGORY_13:  { name: 'Aerosols', value: 13 },
    CATEGORY_14:  { name: 'Trace gases (e.g. Ozone, CO2)', value: 14 },
    CATEGORY_15:  { name: 'Radar', value: 15 },
    CATEGORY_16:  { name: 'Forecast Radar Imagery', value: 16 },
    CATEGORY_17:  { name: 'Electrodynamics', value: 17 },
    CATEGORY_18:  { name: 'Nuclear/radiology', value: 18 },
    CATEGORY_19:  { name: ' Physical atmospheric Properties', value: 19 },
    CATEGORY_20:  { name: 'Atmospheric Chemical Constituents', value: 20 },
    CATEGORY_190: { name: 'CCITT IA5 string', value: 190 },
    CATEGORY_191: { name: 'Miscellaneous', value: 191 },
    CATEGORY_192: { name: 'Covariance', value: 192 },
    CATEGORY_255: { name: 'Missing', value: 255 },
  }),

  // Code Table 4.2-0.2 Discipline 0 (Meteorological) Category 2 (Momentum)
  MeteorologicalProductsMomentumParameter: Object.freeze({
    PARAMETER_0:   { name: 'Wind Direction (from which blowing)', value: 0, unit: '°', abbrev: 'WDIR' },
    PARAMETER_1:   { name: 'Wind Speed', value: 1, unit: 'm s-1', abbrev: 'WIND' },
    PARAMETER_2:   { name: 'U-Component of Wind', value: 2, unit: 'm s-1', abbrev: 'UGRD' },
    PARAMETER_3:   { name: 'V-Component of Wind', value: 3, unit:'m s-1', abbrev: 'VGRD ' },
    PARAMETER_4:   { name: 'Stream Function', value: 4, unit: 'm2 s-1', abbrev: 'STRM' },
    PARAMETER_5:   { name: 'Velocity Potential', value: 5, unit: 'm2 s-1', abbrev: 'VPOT' },
    PARAMETER_6:   { name: 'Montgomery Stream Function', value: 6, unit:'m2 s-2', abbrev: 'MNTSF ' },
    PARAMETER_7:   { name: 'Sigma Coordinate Vertical Velocity', value: 7, unit: 's-1', abbrev: 'SGCVV' },
    PARAMETER_8:   { name: 'Vertical Velocity (Pressure)', value: 8, unit: 'Pa s-1', abbrev: 'VVEL' },
    PARAMETER_9:   { name: 'Vertical Velocity (Geometric)', value: 9, unit:'m s-1', abbrev: 'DZDT' },
    PARAMETER_10:  { name: 'Absolute Vorticity', value: 10, unit: 's-1', abbrev: 'ABSV' },
    PARAMETER_11:  { name: 'Absolute Divergence', value: 11, unit: 's-1', abbrev: 'ABSD' },
    PARAMETER_12:  { name: 'Relative Vorticity', value: 12, unit: 's-1', abbrev: 'RELV' },
    PARAMETER_13:  { name: 'Relative Divergence', value: 13, unit: 's-1', abbrev: 'RELD' },
    PARAMETER_14:  { name: 'Potential Vorticity', value: 14, unit: 'K m2 kg-1 s-1', abbrev: 'PVORT' },
    PARAMETER_15:  { name: 'Vertical U-Component Shear', value: 15, unit: 's-1', abbrev: 'VUCSH' },
    PARAMETER_16:  { name: 'Vertical V-Component Shear', value: 16, unit: 's-1', abbrev: 'VVCSH' },
    PARAMETER_17:  { name: 'Momentum Flux, U-Component', value: 17, unit:'N m-2', abbrev: 'UFLX' },
    PARAMETER_18:  { name: 'Momentum Flux, V-Component', value: 18, unit:'N m-2', abbrev: 'VFLX' },
    PARAMETER_19:  { name: 'Wind Mixing Energy', value: 19, unit: 'J', abbrev: 'WMIXE' },
    PARAMETER_20:  { name: 'Boundary Layer Dissipation', value: 20, unit: 'W m-2', abbrev: 'BLYDP' },
    PARAMETER_22:  { name: 'Wind Speed (Gust)', value: 22, unit: 'm s-1', abbrev: 'GUST' },
    PARAMETER_23:  { name: 'U-Component of Wind (Gust)', value: 23, unit:'m s-1', abbrev: 'UGUST' },
    PARAMETER_24:  { name: 'V-Component of Wind (Gust)', value: 24, unit:'m s-1', abbrev: 'VGUST' },
    PARAMETER_25:  { name: 'Vertical Speed Shear', value: 25, unit:'s-1', abbrev: 'VWSH' },
    PARAMETER_26:  { name: 'Horizontal Momentum Flux', value: 26, unit:'N m-2', abbrev: 'MFLX' },
    PARAMETER_27:  { name: 'U-Component Storm Motion', value: 27, unit:'m s-1', abbrev: 'USTM' },
    PARAMETER_28:  { name: 'V-Component Storm Motion', value: 28, unit:'m s-1', abbrev: 'VSTM' },
    PARAMETER_29:  { name: 'Drag Coefficient', value: 29, unit:'Numeric', abbrev: 'CD' },
    PARAMETER_30:  { name: 'Frictional Velocity', value: 30, unit:'m s-1', abbrev: 'FRICV' },
    PARAMETER_31:  { name: 'Turbulent Diffusion Coefficient for Momentum', value: 31, unit:'m2 s-1', abbrev: 'TDCMOM' },
    PARAMETER_32:  { name: 'Eta Coordinate Vertical Velocity', value: 32, unit:'s-1', abbrev: 'ETACVV' },
    PARAMETER_33:  { name: 'Wind Fetch', value: 33, unit:'m', abbrev: 'WINDF' },
    PARAMETER_34:  { name: 'Normal Wind Component', value: 34, unit: 'm s-1', abbrev: 'NWIND' },
    PARAMETER_35:  { name: 'Tangential Wind Component', value: 35, unit:'m s-1', abbrev: 'TWIND' },
    PARAMETER_36:  { name: 'Amplitude Function for Rossby Wave Envelope for Meridional Wind', value: 36, unit:'m s-1', abbrev: 'AFRWE' },
    PARAMETER_37:  { name: 'Northward Turbulent Surface Stress', value: 37, unit:'N m-2 s', abbrev: 'NTSS' },
    PARAMETER_38:  { name: 'Eastward Turbulent Surface Stress', value: 38, unit:'N m-2 s', abbrev: 'ETSS' },
    PARAMETER_39:  { name: 'Eastward Wind Tendency Due to Parameterizations', value: 39, unit:'m s-2', abbrev: 'EWTPARM' },
    PARAMETER_40:  { name: 'Northward Wind Tendency Due to Parameterizations', value: 40, unit:'m s-2', abbrev: 'NWTPARM' },
    PARAMETER_41:  { name: 'U-Component of Geostrophic Wind', value: 41, unit:'m s-1', abbrev: 'UGWIND' },
    PARAMETER_42:  { name: 'V-Component of Geostrophic Wind', value: 42, unit:'m s-1', abbrev: 'VGWIND' },
    PARAMETER_43:  { name: 'Geostrophic Wind Direction', value: 43, unit:'°', abbrev: 'GEOWD' },
    PARAMETER_44:  { name: 'Geostrophic Wind Speed', value: 44, unit:'m s-1', abbrev: 'GEOWS' },
    PARAMETER_45:  { name: 'Unbalanced Component of Divergence', value: 45, unit:'s-1', abbrev: 'UNDIV' },
    PARAMETER_46:  { name: 'Vorticity Advection', value: 46, unit:'s-2', abbrev: 'VORTADV' },
    PARAMETER_192: { name: 'Vertical Speed Shear', value: 192, unit:'s-1', abbrev: 'VWSH' },
    PARAMETER_193: { name: 'Horizontal Momentum Flux', value: 193, unit:'N m-2', abbrev: 'MFLX' },
    PARAMETER_194: { name: 'U-Component Storm Motion', value: 194, unit:'m s-1', abbrev: 'USTM' },
    PARAMETER_195: { name: 'V-Component Storm Motion', value: 195, unit:'m s-1', abbrev: 'VSTM' },
    PARAMETER_196: { name: 'Drag Coefficient', value: 196, unit: 'non-dim', abbrev: 'CD' },
    PARAMETER_197: { name: 'Frictional Velocity', value: 197, abbrev: 'm s-1', abbrev: 'FRICV' },
    PARAMETER_198: { name: 'Latitude of U Wind Component of Velocity', value: 198, unit:'deg', abbrev: 'LAUV' },
    PARAMETER_199: { name: 'Longitude of U Wind Component of Velocity', value: 199, unit:'deg', abbrev: 'LOUV' },
    PARAMETER_200: { name: 'Latitude of V Wind Component of Velocity', value: 200, unit:'deg', abbrev: 'LAVV' },
    PARAMETER_201: { name: 'Longitude of V Wind Component of Velocity', value: 201, unit:'deg', abbrev: 'LOVV' },
    PARAMETER_202: { name: 'Latitude of Presure Point', value: 202, unit:'deg', abbrev: 'LAPP' },
    PARAMETER_203: { name: 'Longitude of Presure Point', value: 203, unit:'deg', abbrev: 'LOPP' },
    PARAMETER_204: { name: 'Vertical Eddy Diffusivity Heat exchange', value: 204, unit:'m2 s-1', abbrev: 'VEDH' },
    PARAMETER_205: { name: 'Covariance between Meridional and Zonal Components of the wind.', value: 205, unit:'m2 s-2', abbrev: 'COVMZ' },
    PARAMETER_206: { name: 'Covariance between Temperature and Zonal Components of the wind.', value: 206, unit:'K*m s-1', abbrev: 'COVTZ' },
    PARAMETER_207: { name: 'Covariance between Temperature and Meridional Components of the wind.', value: 207, unit:'K*m s-1', abbrev: 'COVTM' },
    PARAMETER_208: { name: 'Vertical Diffusion Zonal Acceleration', value: 208, unit: 'm s-2', abbrev: 'VDFUA' },
    PARAMETER_209: { name: 'Vertical Diffusion Meridional Acceleration', value: 209, unit: 'm s-2', abbrev: 'VDFVA' },
    PARAMETER_210: { name: 'Gravity wave drag zonal acceleration', value: 210, unit: 'm s-2', abbrev: 'GWDU' },
    PARAMETER_211: { name: 'Gravity wave drag meridional acceleration', value: 211, unit: 'm s-2', abbrev: 'GWDV' },
    PARAMETER_212: { name: 'Convective zonal momentum mixing acceleration', value: 212, unit: 'm s-2', abbrev: 'CNVU' },
    PARAMETER_213: { name: 'Convective meridional momentum mixing acceleration', value: 213, unit: 'm s-2', abbrev: 'CNVV' },
    PARAMETER_214: { name: 'Tendency of vertical velocity', value: 214, unit:'m s-2', abbrev: 'WTEND' },
    PARAMETER_215: { name: 'Omega (Dp/Dt) divide by density', value: 215, unit:'K', abbrev: 'OMGALF' },
    PARAMETER_216: { name: 'Convective Gravity wave drag zonal acceleration', value: 216, unit: 'm s-2', abbrev: 'CNGWDU' },
    PARAMETER_217: { name: 'Convective Gravity wave drag meridional acceleration', value: 217, unit: 'm s-2', abbrev: 'CNGWDV' },
    PARAMETER_218: { name: 'Velocity Point Model Surface', value: 218, abbrev:'LMV' },
    PARAMETER_219: { name: 'Potential Vorticity (Mass-Weighted)', value: 219, unit:'1/s/m', abbrev: 'PVMWW' },
    PARAMETER_220: { name: 'Hourly Maximum of Upward Vertical Velocity in the lowest 400hPa', value: 220, unit:'m s-1', abbrev: 'MAXUVV' },
    PARAMETER_221: { name: 'Hourly Maximum of Downward Vertical Velocity in the lowest 400hPa', value: 221, unit:'m s-1', abbrev: 'MAXDVV' },
    PARAMETER_222: { name: 'U Component of Hourly Maximum 10m Wind Speed', value: 222, unit:'m s-1', abbrev: 'MAXUW' },
    PARAMETER_223: { name: 'V Component of Hourly Maximum 10m Wind Speed', value: 223, unit:'m s-1', abbrev: 'MAXVW' },
    PARAMETER_224: { name: 'Ventilation Rate', value: 224, unit:'m2 s-1', abbrev: 'VRATE' },
    PARAMETER_225: { name: 'Transport Wind Speed', value: 225, unit:'m s-1', abbrev: 'TRWSPD' },
    PARAMETER_226: { name: 'Transport Wind Direction', value: 226, unit:'Deg', abbrev: 'TRWDIR' },
    PARAMETER_227: { name: 'Earliest Reasonable Arrival Time (10% exceedance)', value: 227, unit:'s', abbrev: 'TOA10' },
    PARAMETER_228: { name: 'Most Likely Arrival Time (50% exceedance)', value: 228, unit:'s', abbrev: 'TOA50' },
    PARAMETER_229: { name: 'Most Likely Departure Time (50% exceedance)', value: 229, unit:'s', abbrev: 'TOD50' },
    PARAMETER_230: { name: 'Latest Reasonable Departure Time (90% exceedance)', value: 230, unit:'s', abbrev: 'TOD90' },
    PARAMETER_231: { name: 'Tropical Wind Direction', value: 231, unit:'°', abbrev: 'TPWDIR' },
    PARAMETER_232: { name: 'Tropical Wind Speed', value: 232, unit:'m s-1', abbrev: 'TPWSPD' },
    PARAMETER_255: { name: 'Missing', value: 255 },
  }),

  // Code Table 4.3 Type of generating process
  GeneratingProcessType: Object.freeze({
    TYPE_0:   { name: 'Analysis', value: 0 },
    TYPE_1:   { name: 'Initialization', value: 1 },
    TYPE_2:   { name: 'Forecast', value: 2 },
    TYPE_3:   { name: 'Bias Corrected Forecast', value: 3 },
    TYPE_4:   { name: 'Ensemble Forecast', value: 4 },
    TYPE_5:   { name: 'Probability Forecast', value: 5 },
    TYPE_6:   { name: 'Forecast Error', value: 6 },
    TYPE_7:   { name: 'Analysis Error', value: 7 },
    TYPE_8:   { name: 'Observation', value: 8 },
    TYPE_9:   { name: 'Climatological', value: 9 },
    TYPE_10:  { name: 'Probability-Weighted Forecast', value: 10 },
    TYPE_11:  { name: 'Bias-Corrected Ensemble Forecast', value: 11 },
    TYPE_12:  { name: 'Post-processed Analysis ', value: 12 },
    TYPE_13:  { name: 'Post-processed Forecast', value: 13 },
    TYPE_14:  { name: 'Nowcast', value: 14 },
    TYPE_15:  { name: 'Hindcast', value: 15 },
    TYPE_16:  { name: 'Physical Retrieval', value: 16 },
    TYPE_17:  { name: 'Regression Analysis', value: 17 },
    TYPE_18:  { name: 'Difference Between Two Forecasts', value: 18 },
    TYPE_192: { name: 'Forecast Confidence Indicator', value: 192 },
    TYPE_193: { name: 'Probability-matched Mean', value: 193 },
    TYPE_194: { name: 'Neighborhood Probability', value: 194 },
    TYPE_195: { name: 'Bias-Corrected and Downscaled Ensemble Forecast', value: 195 },
    TYPE_196: { name: 'Perturbed Analysis for Ensemble Initialization', value: 196 },
    TYPE_197: { name: 'Ensemble Agreement Scale Probability', value: 197 },
    TYPE_198: { name: 'Post-Processed Deterministic-Expert-Weighted Forecast', value: 198 },
    TYPE_199: { name: 'Ensemble Forecast Based on Counting', value: 199 },
    TYPE_200: { name: 'Local Probability-matched Mean', value: 200 },
    TYPE_255: { name: 'Missing', value: 255 },
  }),

  // Code Table 5.0
  DataRepresentationTemplateNumber: Object.freeze({
    GRID_SIMPLE:          { name: 'Grid point data - simple packing', value: 0 },
    MATRIX_SIMPLE:           { name: 'Matrix value - simple packing', value: 1 },
    GRID_COMPLEX:           { name: '	Grid point data - complex packing', value: 2 },
    GRID_COMPLEX_SPATIAL_DIFF:           { name: 'Grid point data - complex packing and spatial differencing', value: 3 },
    SPECTRAL_SIMPLE:           { name: 'Spectral data - simple packing', value: 50 },
    SPHERICAL_COMPLEX:           { name: 'Spherical harmonics data - complex packing', value: 51 },
    MISSING:            { name: 'Missing', value: 255 },
  }),

  // Code Table 6.0
  BitMapIndicator: Object.freeze({
    SPECIFIED:          { name: 'Use specified bit-map', value: 0 },
    PREVIOUS:           { name: 'Use bit-map defined previously', value: 254 },
    MISSING:            { name: 'Missing', value: 255 },
  }),
}
