// Work around older JS's w/out freeze()
if(Object.freeze === undefined) { Object.freeze = function(x) { return x; } }

// Attempt to lookup a value in the specified table. If the optional
// throwIfNotFound is truthy throw an error if no match is found otherwise
// return the original value. FIXME: This is needlessly slow!
exports.lookup = function(table, value, throwIfNotFound) {
  for(var k in table) {
    if(table[k].value === value) { return table[k]; }
  }
  return value;
}

exports.tables = {
  // Code Table 0.0
  Discipline: Object.freeze({
    METEOROLOGICAL:     { name: 'Meteorological Products', value: 0 },
    HYDROLOGICAL:       { name: 'Hydrological Products', value: 1 },
    LAND_SURFACE:       { name: 'Land Surface Products', value: 2 },
    SATELLITE_REMOTE:   { name: 'Satellite Remote Sensing Products', value: 3 },
    SPACE:              { name: 'Space Weather Products', value: 4 },
    OCEANOGRAPHIC:      { name: 'Oceanographic Products ', value: 10 },
    MISSING:            { name: 'Missing', value: 255 },
  }),

  // Code Table 1.0
  Center: Object.freeze({
    MELBOURNE_1: { name: 'Melbourne (WMC)', value: 1 },
    MELBOURNE_2: { name: 'Melbourne (WMC)', value: 2 },
    MELBOURNE_3: { name: 'Melbourne (WMC)', value: 3 },
    MELBOURNE_4: { name: 'Melbourne (RSMC)', value: 67 },
    MOSCOW_1: { name: 'Moscow (WMC)', value: 4 },
    MOSCOW_2: { name: 'Moscow (WMC)', value: 5 },
    MOSCOW_3: { name: 'Moscow (WMC)', value: 6 },
    MOSCOW_4: { name: 'Moscow (RSMC/RAFC)', value: 76 },
    US_NCEP: { name: 'US National Weather Service - NCEP (WMC)', value: 7 },
    US_NWSTG: { name: 'US National Weather Service - NWSTG (WMC)', value: 8 },
    US_OTHER: { name: 'US National Weather Service - Other (WMC)', value: 9 },
    CAIRO_1: { name: 'Cairo (RSMC/RAFC)', value: 10 },
    CAIRO_2: { name: 'Cairo (RSMC/RAFC)', value: 11 },
    DAKAR_1: { name: 'Dakar (RSMC/RAFC)', value: 12 },
    DAKAR_2: { name: 'Dakar (RSMC/RAFC)', value: 13 },
    NAIROBI_1: { name: 'Nairobi (RSMC/RAFC)', value: 14 },
    NAIROBI_2: { name: 'Nairobi (RSMC/RAFC)', value: 15 },
    CASABLANCA: { name: 'Casablanca (RSMC)', value: 16 },
    TUNIS: { name: 'Tunis (RSMC)', value: 17 },
    TUNIS_CASABLANCA_1: { name: 'Tunis-Casablanca (RSMC)', value: 18 },
    TUNIS_CASABLANCA_2: { name: 'Tunis-Casablanca (RSMC)', value: 19 },
    LAS_PALMAS: { name: 'Las Palmas (RAFC)', value: 20 },
    ALGIERS: { name: 'Algiers (RSMC)', value: 21 },
    ACMAD: { name: 'ACMAD', value: 22 },
    MOZAMBIQUE: { name: 'Mozambique (NMC)', value: 23 },
    PRETORIA: { name: 'Pretoria (RSMC)', value: 24 },
    LA_REUNION: { name: 'La Reunion (RSMC)', value: 25 },
    KHABAROVSK_1: { name: 'Khabarovsk (RSMC)', value: 26 },
    KHABAROVSK_2: { name: 'Khabarovsk (RSMC)', value: 27 },
    NEW_DELHI_1: { name: 'New Delhi (RSMC/RAFC)', value: 28 },
    NEW_DELHI_2: { name: 'New Delhi (RSMC/RAFC)', value: 29 },
    NOVOSIBIRSK_1: { name: 'Novosibirsk (RSMC)', value: 30 },
    NOVOSIBIRSK_2: { name: 'Novosibirsk (RSMC)', value: 31 },
    TASHKENT: { name: 'Tashkent (RSMC)', value: 32 },
    JEDDAH: { name: 'Jeddah (RSMC)', value: 33 },
    TOKYO_1: { name: 'Tokyo (RSMC), Japanese Meteorological Agency', value: 34 },
    TOKYO_2: { name: 'Tokyo (RSMC), Japanese Meteorological Agency', value: 35 },
    BANKOK: { name: 'Bankok', value: 36 },
    ULAN_BATOR: { name: 'Ulan Bator', value: 37 },
    BEIJING_1: { name: 'Beijing (RSMC)', value: 38 },
    BEIJING_2: { name: 'Beijing (RSMC)', value: 39 },
    SEOUL: { name: 'Seoul', value: 40 },
    BUENOS_AIRES_1: { name: 'Buenos Aires (RSMC/RAFC)', value: 41 },
    BUENOS_AIRES_2: { name: 'Buenos Aires (RSMC/RAFC)', value: 42 },
    BRASILIA_1: { name: 'Brasilia (RSMC/RAFC)', value: 43 },
    BRASILIA_2: { name: 'Brasilia (RSMC/RAFC)', value: 44 },
    SANTIAGO: { name: 'Santiago', value: 45 },
    BRAZILIAN_SPACE_AGENCY: { name: 'Brazilian Space Agency - INPE', value: 46 },
    COLUMBIA: { name: 'Columbia (NMC)', value: 47 },
    ECUADOR: { name: 'Ecuador (NMC)', value: 48 },
    PERU: { name: 'Peru (NMC)', value: 49 },
    VENEZUELA: { name: 'Venezuela (NMC)', value: 50 },
    MIAMI: { name: 'Miami (RSMC/RAFC)', value: 51 },
    MIAMI_NATIONAL_HURRICANE_CENTER: { name: 'Miami (RSMC), National Hurricane Center', value: 52 },
    MONTREAL_1: { name: 'Canadian Meteorological Service - Montreal (RSMC)', value: 53 },
    MONTREAL_2: { name: 'Canadian Meteorological Service - Montreal (RSMC)', value: 54 },
    SAN_FRANCISCO: { name: 'San Francisco', value: 55 },
    ARINC_CENTER: { name: 'ARINC Center', value: 56 },
    US_AIR_FORCE: { name: 'US Air Force - Air Force Global Weather Center', value: 57 },
    MONTEREY: { name: 'Fleet Numerical Meteorology and Oceanography Center,Monterey,CA,USA', value: 58 },
    NOAA: { name: 'The NOAA Forecast Systems Lab, Boulder, CO, USA', value: 59 },
    NCAR: { name: 'National Center for Atmospheric Research (NCAR), Boulder, CO', value: 60 },
    ARGOS: { name: 'Service ARGOS - Landover, MD, USA', value: 61 },
    US_NAVAL_OCEANOGRAPHIC_OFFICE: { name: 'US Naval Oceanographic Office', value: 62 },
    INTERNATIONAL_RESEARCH_INSTITUDE_FOR_CLIMATE_AND_SOCIETY: { name: 'International Research Institude for Climate and Society', value: 63 },
    HONOLULU: { name: 'Honolulu', value: 64 },
    DARWIN_1: { name: 'Darwin (RSMC)', value: 65 },
    DARWIN_2: { name: 'Darwin (RSMC)', value: 66 },
    WELLINGTON_1: { name: 'Wellington (RSMC/RAFC)', value: 69 },
    WELLINGTON_2: { name: 'Wellington (RSMC/RAFC)', value: 70 },
    NADI: { name: 'Nadi (RSMC)', value: 71 },
    SINGAPORE: { name: 'Singapore', value: 72 },
    MALAYSIA: { name: 'Malaysia (NMC)', value: 73 },
    UK_MET_OFFICE_EXETER_1: { name: 'U.K. Met Office - Exeter (RSMC)', value: 74 },
    UK_MET_OFFICE_EXETER_2: { name: 'U.K. Met Office - Exeter (RSMC)', value: 75 },
    OFFENBACH_1: { name: 'Offenbach (RSMC)', value: 78 },
    OFFENBACH_2: { name: 'Offenbach (RSMC)', value: 79 },
    ROME_1: { name: 'Rome (RSMC)', value: 80 },
    ROME_2: { name: 'Rome (RSMC)', value: 81 },
    NORRKOPING_1: { name: 'Norrkoping', value: 82 },
    NORRKOPING_2: { name: 'Norrkoping', value: 83 },
    FRENCH_WEATHER_SERVICE_TOULOUSE_1: { name: 'French Weather Service - Toulouse', value: 84 },
    FRENCH_WEATHER_SERVICE_TOULOUSE_2: { name: 'French Weather Service - Toulouse', value: 85 },
    HELSINKI: { name: 'Helsinki', value: 86 },
    BELGRADE: { name: 'Belgrade', value: 87 },
    OSLO: { name: 'Oslo', value: 88 },
    PRAGUE: { name: 'Prague', value: 89 },
    EPISKOPI: { name: 'Episkopi', value: 90 },
    ANKARA: { name: 'Ankara', value: 91 },
    FRANKFURT: { name: 'Frankfurt/Main (RAFC)', value: 92 },
    LONDON: { name: 'London (WAFC)', value: 93 },
    COPENHAGEN: { name: 'Copenhagen', value: 94 },
    ROTA: { name: 'Rota', value: 95 },
    ATHENS: { name: 'Athens', value: 96 },
    EUROPEAN_SPACE_AGENCY: { name: 'European Space Agency (ESA)', value: 97 },
    EUROPEAN_CENTER_FOR_Medium_RANGE_WEATHER_FORECASTS: { name: 'European Center for Medium-Range Weather Forecasts (RSMC)', value: 98 },
    DE_BILT: { name: 'De Bilt, Netherlands', value: 99 },
    BRAZZAVILLE: { name: 'Brazzaville', value: 100 },
    ABIDJAN: { name: 'Abidjan', value: 101 },
    LIBYAN_ARAB_JAMAHIRIYA: { name: 'Libyan Arab Jamahiriya (NMC)', value: 102 },
    MADAGASCAR: { name: 'Madagascar (NMC)', value: 103 },
    MAURITIUS: { name: 'Mauritius (NMC)', value: 104 },
    NIGER: { name: 'Niger (NMC)', value: 105 },
    SEYCHELLES: { name: 'Seychelles (NMC)', value: 106 },
    UGANDA: { name: 'Uganda (NMC)', value: 107 },
    TANZANIA: { name: 'United Republic of Tanzania (NMC)', value: 108 },
    ZIMBABWE: { name: 'Zimbabwe (NMC)', value: 109 },
    HONG_KONG: { name: 'Hong-Kong', value: 110 },
    AFGHANISTAN: { name: 'Afghanistan (NMC)', value: 111 },
    BAHRAIN: { name: 'Bahrain (NMC)', value: 112 },
    BANGLADESH: { name: 'Bangladesh (NMC)', value: 113 },
    BHUTAN: { name: 'Bhutan (NMC)', value: 114 },
    CAMBODIA: { name: 'Cambodia (NMC)', value: 115 },
    KOREA: { name: '	Democratic People\'s Republic of Korea (NMC)', value: 116 },
    IRAN: { name: 'Islamic Republic of Iran (NMC)', value: 117 },
    IRAQ: { name: 'Iraq (NMC)', value: 118 },
    KAZAKHSTAN: { name: 'Kazakhstan (NMC)', value: 119 },
    KUWAIT: { name: 'Kuwait (NMC)', value: 120 },
    KYRGYZ_REPUBLIC: { name: 'Kyrgyz Republic (NMC)', value: 121 },
    LAO: { name: 'Lao People\'s Democratic Republic (NMC)', value: 122 },
    MACAO: { name: 'Macao, China', value: 123 },
    MALDIVES: { name: 'Maldives (NMC)', value: 124 },
    MYANMAR: { name: 'Myanmar (NMC)', value: 125 },
    NEPAL: { name: 'Nepal (NMC)', value: 126 },
    OMAN: { name: 'Oman (NMC)', value: 127 },
    PAKISTAN: { name: 'Pakistan (NMC)', value: 128 },
    QATAR: { name: 'Qatar (NMC)', value: 129 },
    YEMEN: { name: 'Yemen (NMC)', value: 130 },
    SRI_LANKA: { name: 'Sri Lanka (NMC)', value: 131 },
    TAJIKISTAN: { name: 'Tajikistan (NMC)', value: 132 },
    TURKMENISTAN: { name: 'Turkmenistan (NMC)', value: 133 },
    UNITED_ARAB_EMIRATES: { name: 'United Arab Emirates (NMC)', value: 134 },
    UZBEKISTAN: { name: 'Uzbekistan (NMC)', value: 135 },
    VIET_NAM: { name: 'Viet Nam (NMC)', value: 136 },
    BOLIVIA: { name: 'Bolivia (NMC)', value: 140 },
    GUYANA: { name: 'Guyana (NMC)', value: 141 },
    PARAGUAY: { name: 'Paraguay (NMC)', value: 142 },
    SURINAME: { name: 'Suriname (NMC)', value: 143 },
    URUGUAY: { name: 'Uruguay (NMC)', value: 144 },
    FRENCH_GUYANA: { name: 'French Guyana', value: 145 },
    BRAZILIAN_NAVY_HYDROGRAPHIC_CENTER: { name: 'Brazilian Navy Hydrographic Center', value: 146 },
    NATIONAL_COMMISSION_ON_SPACE_ACTIVITIES_ARGENTINA: { name: 'National Commission on Space Activities - Argentina', value: 147 },
    BRAZILIAN_DEPARTMENT_OF_AIRSPACE_CONTROL_DECEA: { name: 'Brazilian Department of Airspace Control - DECEA', value: 148 },
    ANTIGUA_AND_BARBUDA: { name: 'Antigua and Barbuda (NMC)', value: 150 },
    BAHAMAS: { name: 'Bahamas (NMC)', value: 151 },
    BARBADOS: { name: 'Barbados (NMC)', value: 152 },
    BELIZE: { name: 'Belize (NMC)', value: 153 },
    BRITISH_CARIBBEAN_TERRITORIES_CENTER: { name: 'British Caribbean Territories Center', value: 154 },
    SAN_JOSE: { name: 'San Jose', value: 155 },
    CUBA: { name: 'Cuba (NMC)', value: 156 },
    DOMINICA: { name: 'Dominica (NMC)', value: 157 },
    DOMINICAN_REPUBLIC: { name: 'Dominican Republic (NMC)', value: 158 },
    EL_SALVADOR: { name: 'El Salvador (NMC)', value: 159 },
    US_NOAA_NESDIS: { name: 'US NOAA/NESDIS', value: 160 },
    US_NOAA_OFFICE_OF_OCEANIC_AND_ATMOSPHERIC_RESEARCH: { name: 'US NOAA Office of Oceanic and Atmospheric Research', value: 161 },
    GUATEMALA: { name: 'Guatemala (NMC)', value: 162 },
    HAITI: { name: 'Haiti (NMC)', value: 163 },
    HONDURAS: { name: 'Honduras (NMC)', value: 164 },
    JAMAICA: { name: 'Jamaica (NMC)', value: 165 },
    MEXICO_CITY: { name: 'Mexico City', value: 166 },
    NETHERLANDS_ANTILLES_AND_ARUBA: { name: 'Netherlands Antilles and Aruba (NMC)', value: 167 },
    NICARAGUA: { name: 'Nicaragua (NMC)', value: 168 },
    PANAMA: { name: 'Panama (NMC)', value: 169 },
    SAINT_LUCIA: { name: 'Saint Lucia (NMC)', value: 170 },
    TRINIDAD_AND_TOBAGO: { name: 'Trinidad and Tobago (NMC)', value: 171 },
    FRENCH_DEPARTMENTS_IN_RA_IV: { name: 'French Departments in RA IV', value: 172 },
    US_NATIONAL_AERONAUTICS_AND_SPACE_ADMINISTRATION: { name: 'US National Aeronautics and Space Administration (NASA)', value: 173 },
    ISDM: { name: 'Integrated System Data Management/Marine Environmental Data Service (ISDM/MEDS) - Canada', value: 174 },
    US_COOPERATIVE_INSTITUDE_FOR_METEOROLOGICAL_SATELLITE_STUDIES: { name: 'US Cooperative Institude for Meteorological Satellite Studies', value: 176 },
    COOK_ISLANDS: { name: 'Cook Islands (NMC)', value: 190 },
    FRENCH_POLYNESIA: { name: 'French Polynesia (NMC)', value: 191 },
    TONGA: { name: 'Tonga (NMC)', value: 192 },
    VANUATU: { name: 'Vanuatu (NMC)', value: 193 },
    BRUNEI: { name: 'Brunei (NMC)', value: 194 },
    INDONESIA: { name: 'Indonesia (NMC)', value: 195 },
    KIRIBATI: { name: 'Kiribati (NMC)', value: 196 },
    MICRONESIA: { name: 'Federated States of Micronesia (NMC)', value: 197 },
    NEW_CALEDONIA: { name: 'New Caledonia (NMC)', value: 198 },
    NIUE: { name: 'Niue', value: 199 },
    PAPUA_NEW_GUINEA: { name: 'Papua New Guinea (NMC)', value: 200 },
    PHILIPPINES: { name: 'Philippines (NMC)', value: 201 },
    SAMOA: { name: 'Samoa (NMC)', value: 202 },
    SOLOMON_ISLANDS: { name: 'Solomon Islands (NMC)', value: 203 },
    NEW_ZEALAND: { name: 'Narional Institude of Water and Atmospheric Research - New Zealand', value: 204 },
    FRASCATI: { name: 'Frascati (ESA/ESRIN)', value: 210 },
    LANION: { name: 'Lanion', value: 211 },
    LISBON: { name: 'Lisbon', value: 212 },
    REYKJAVIK: { name: 'Reykjavik', value: 213 },
    MADRID: { name: 'Madrid', value: 214 },
    ZURICH: { name: 'Zurich', value: 215 },
    ARGOS_TOULOUSE: { name: 'Service ARGOS - Toulouse', value: 216 },
    BRATISLAVA: { name: 'Bratislava', value: 217 },
    BUDAPEST: { name: 'Budapest', value: 218 },
    LJUBLJANA: { name: 'Ljubljana', value: 219 },
    WARSAW: { name: 'Warsaw', value: 220 },
    ZAGREB: { name: 'Zagreb', value: 221 },
    ALBANIA: { name: 'Albania (NMC)', value: 222 },
    ARMENIA: { name: 'Armenia (NMC)', value: 223 },
    AUSTRIA: { name: 'Austria (NMC)', value: 224 },
    AZERBAIJAN: { name: 'Azerbaijan (NMC)', value: 225 },
    BELARUS: { name: 'Belarus (NMC)', value: 226 },
    BELGIUM: { name: 'Belgium (NMC)', value: 227 },
    BOSNIA_HERZEGOVINA: { name: 'Bosnia and Herzegovina (NMC)', value: 228 },
    BULGARIA: { name: 'Bulgaria (NMC)', value: 229 },
    CYPRUS: { name: 'Cyprus (NMC)', value: 230 },
    ESTONIA: { name: 'Estonia (NMC)', value: 231 },
    GEORGIA: { name: 'Georgia (NMC)', value: 232 },
    DUBLIN: { name: 'Dublin', value: 233 },
    ISRAEL: { name: 'Israel (NMC)', value: 234 },
    JORDAN: { name: 'Jordan (NMC)', value: 235 },
    LATVIA: { name: 'Latvia (NMC)', value: 236 },
    LEBANON: { name: 'Lebanon (NMC)', value: 237 },
    LITHUANIA: { name: 'Lithuania (NMC)', value: 238 },
    LUXEMBOURG: { name: 'Luxembourg', value: 239 },
    MALTA: { name: 'Malta (NMC)', value: 240 },
    MONACO: { name: 'Monaco', value: 241 },
    ROMANIA: { name: 'Romania (NMC)', value: 242 },
    SYRIAN: { name: 'Syrian Arab Republic (NMC)', value: 243 },
    MACEDONIA: { name: 'The former Yugoslav Republic of Macedonia (NMC)', value: 244 },
    UKRAINE: { name: 'Ukraine (NMC)', value: 245 },
    MOLDOVA: { name: 'Republic of Moldova (NMC)', value: 246 },
    OPERA: { name: 'Operational Programme for the Exchange of Weather RAdar Information (OPERA) - EUMETNET', value: 247 },
    CONSORTIUM_FOR_SMALL_SCALE_MODELLING: { name: 'COnsortium for Small scale MOdelling (COSMO)', value: 250 },
    EUMETSAT_OPERATIONS_CENTER: { name: 'EUMETSAT Operations Center', value: 254 },
    MISSING: { name: 'Missing Value', value: 255 },
  }),

  // Code Table 1.2
  ReferenceTimeSignificance: Object.freeze({
    ANALYSIS:           { name: 'Analysis', value: 0 },
    START_OF_FORECAST:  { name: 'Start of Forecast', value: 1 },
    VERIFICATION:       { name: 'Verification time of forecast', value: 2 },
    OBSERVATION:        { name: 'Observations time', value: 3 },
    MISSING:            { name: 'Missing', value: 255 },
  }),

  // Code Table 1.3
  ProductionStatus: Object.freeze({
    OPERATIONAL:        { name: 'Operational products', value: 0 },
    OPERATIONAL_TEST:   { name: 'Operational test products', value: 1 },
    RESEARCH:           { name: 'Research products', value: 2 },
    REANALYSIS:         { name: 'Re-analysis', value: 3 },
    MISSING:            { name: 'Missing', value: 255 },
  }),

  // Code Table 1.4
  Type: Object.freeze({
    ANALYSIS:           { name: 'Analysis products', value: 0 },
    FORECAST:           { name: 'Forecast products', value: 1 },
    ANALYSIS_AND_FORECAST:  { name: 'Analysis and forecast products', value: 2 },
    CONTROL:            { name: 'Control forecast products', value: 3 },
    PERTURBED:          { name: 'Perturbed forecast products', value: 4 },
    CONTROL_AND_PERTURBED:  { name: 'Control and perturbed forecast products', value: 5 },
    SATELLITE:          { name: 'Processed satellite observations', value: 6 },
    RADAR:              { name: 'Processed radar observations', value: 7 },
    MISSING:            { name: 'Missing', value: 255 },
  }),

  // Code Table 3.2
  EarthShape: Object.freeze({
    STD_SPHERICAL_1:    { name: 'Earth assumed spherical with radius = 6,367,470.0 m', value: 0 },
    SPHERICAL:          { name: 'Earth assumed spherical with radius specified by data producer', value: 1 },
    IAU_SPHEROID:       { name: 'Earth assumed oblate spheroid with size as determined by IAU in 1965 (major axis = 6,378,160.0 m, minor axis = 6,356,775.0 m, f = 1/297.0)', value: 2 },
    SPHEROID:           { name: 'Earth assumed oblate spheroid with major and minor axes specified by data producer', value: 3 },
    IAG_SPHEROID:       { name: 'Earth assumed oblate spheroid as defined in IAG-GRS80 model (major axis = 6,378,137.0 m, minor axis = 6,356,752.314 m, f = 1/298.257222101)', value: 4 },
    WGS84_SPHEROID:     { name: 'Earth assumed represented by WGS84 (as used by ICAO since 1998)', value: 5 },
    STD_SPHERICAL_2:    { name: 'Earth assumed spherical with radius of 6,371,229.0 m', value: 6 },
    MISSING:            { name: 'Missing', value: 255 },
  }),

  // Code Table 5.0
  DataRepresentationTemplateNumber: Object.freeze({
    GRID_SIMPLE:          { name: 'Grid point data - simple packing', value: 0 },
    MATRIX_SIMPLE:           { name: 'Matrix value - simple packing', value: 1 },
    GRID_COMPLEX:           { name: '	Grid point data - complex packing', value: 2 },
    GRID_COMPLEX_SPATIAL_DIFF:           { name: 'Grid point data - complex packing and spatial differencing', value: 3 },
    SPECTRAL_SIMPLE:           { name: 'Spectral data - simple packing', value: 50 },
    SPHERICAL_COMPLEX:           { name: 'Spherical harmonics data - complex packing', value: 51 },
    MISSING:            { name: 'Missing', value: 255 },
  }),

  // Code Table 6.0
  BitMapIndicator: Object.freeze({
    SPECIFIED:          { name: 'Use specified bit-map', value: 0 },
    PREVIOUS:           { name: 'Use bit-map defined previously', value: 254 },
    MISSING:            { name: 'Missing', value: 255 },
  }),
}
